// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: modules/wal/proto/wal.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WALEntry representa una entrada en el Write-Ahead Log
type WALEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tipo de operación: 1=CREATE, 2=WRITE, 3=DELETE, 4=COMMIT
	OpType uint32 `protobuf:"varint,1,opt,name=op_type,json=opType,proto3" json:"op_type,omitempty"`
	// Nombre de la tabla
	Table string `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	// Clave del registro
	Key string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	// Valor serializado (puede estar vacío para DELETE)
	Value []byte `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	// ID de la transacción (opcional)
	TxId string `protobuf:"bytes,5,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	// Timestamp en nanosegundos desde Unix epoch
	Timestamp int64 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Metadatos adicionales (opcional)
	Metadata      map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WALEntry) Reset() {
	*x = WALEntry{}
	mi := &file_modules_wal_proto_wal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALEntry) ProtoMessage() {}

func (x *WALEntry) ProtoReflect() protoreflect.Message {
	mi := &file_modules_wal_proto_wal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALEntry.ProtoReflect.Descriptor instead.
func (*WALEntry) Descriptor() ([]byte, []int) {
	return file_modules_wal_proto_wal_proto_rawDescGZIP(), []int{0}
}

func (x *WALEntry) GetOpType() uint32 {
	if x != nil {
		return x.OpType
	}
	return 0
}

func (x *WALEntry) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *WALEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WALEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *WALEntry) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *WALEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WALEntry) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// WALBatch para optimizar escrituras en lote
type WALBatch struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Entries        []*WALEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	BatchTimestamp int64                  `protobuf:"varint,2,opt,name=batch_timestamp,json=batchTimestamp,proto3" json:"batch_timestamp,omitempty"`
	BatchId        uint32                 `protobuf:"varint,3,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WALBatch) Reset() {
	*x = WALBatch{}
	mi := &file_modules_wal_proto_wal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALBatch) ProtoMessage() {}

func (x *WALBatch) ProtoReflect() protoreflect.Message {
	mi := &file_modules_wal_proto_wal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALBatch.ProtoReflect.Descriptor instead.
func (*WALBatch) Descriptor() ([]byte, []int) {
	return file_modules_wal_proto_wal_proto_rawDescGZIP(), []int{1}
}

func (x *WALBatch) GetEntries() []*WALEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *WALBatch) GetBatchTimestamp() int64 {
	if x != nil {
		return x.BatchTimestamp
	}
	return 0
}

func (x *WALBatch) GetBatchId() uint32 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

// WALCheckpoint para marcar puntos de recuperación
type WALCheckpoint struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timestamp      int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SequenceNumber uint64                 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	SnapshotPath   string                 `protobuf:"bytes,3,opt,name=snapshot_path,json=snapshotPath,proto3" json:"snapshot_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WALCheckpoint) Reset() {
	*x = WALCheckpoint{}
	mi := &file_modules_wal_proto_wal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALCheckpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALCheckpoint) ProtoMessage() {}

func (x *WALCheckpoint) ProtoReflect() protoreflect.Message {
	mi := &file_modules_wal_proto_wal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALCheckpoint.ProtoReflect.Descriptor instead.
func (*WALCheckpoint) Descriptor() ([]byte, []int) {
	return file_modules_wal_proto_wal_proto_rawDescGZIP(), []int{2}
}

func (x *WALCheckpoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WALCheckpoint) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *WALCheckpoint) GetSnapshotPath() string {
	if x != nil {
		return x.SnapshotPath
	}
	return ""
}

var File_modules_wal_proto_wal_proto protoreflect.FileDescriptor

const file_modules_wal_proto_wal_proto_rawDesc = "" +
	"\n" +
	"\x1bmodules/wal/proto/wal.proto\x12\x05proto\"\x8c\x02\n" +
	"\bWALEntry\x12\x17\n" +
	"\aop_type\x18\x01 \x01(\rR\x06opType\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\x12\x13\n" +
	"\x05tx_id\x18\x05 \x01(\tR\x04txId\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x129\n" +
	"\bmetadata\x18\a \x03(\v2\x1d.proto.WALEntry.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"y\n" +
	"\bWALBatch\x12)\n" +
	"\aentries\x18\x01 \x03(\v2\x0f.proto.WALEntryR\aentries\x12'\n" +
	"\x0fbatch_timestamp\x18\x02 \x01(\x03R\x0ebatchTimestamp\x12\x19\n" +
	"\bbatch_id\x18\x03 \x01(\rR\abatchId\"{\n" +
	"\rWALCheckpoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x04R\x0esequenceNumber\x12#\n" +
	"\rsnapshot_path\x18\x03 \x01(\tR\fsnapshotPathB:Z8github.com/polarysfoundation/polarysdb/modules/wal/protob\x06proto3"

var (
	file_modules_wal_proto_wal_proto_rawDescOnce sync.Once
	file_modules_wal_proto_wal_proto_rawDescData []byte
)

func file_modules_wal_proto_wal_proto_rawDescGZIP() []byte {
	file_modules_wal_proto_wal_proto_rawDescOnce.Do(func() {
		file_modules_wal_proto_wal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_wal_proto_wal_proto_rawDesc), len(file_modules_wal_proto_wal_proto_rawDesc)))
	})
	return file_modules_wal_proto_wal_proto_rawDescData
}

var file_modules_wal_proto_wal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_modules_wal_proto_wal_proto_goTypes = []any{
	(*WALEntry)(nil),      // 0: proto.WALEntry
	(*WALBatch)(nil),      // 1: proto.WALBatch
	(*WALCheckpoint)(nil), // 2: proto.WALCheckpoint
	nil,                   // 3: proto.WALEntry.MetadataEntry
}
var file_modules_wal_proto_wal_proto_depIdxs = []int32{
	3, // 0: proto.WALEntry.metadata:type_name -> proto.WALEntry.MetadataEntry
	0, // 1: proto.WALBatch.entries:type_name -> proto.WALEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_modules_wal_proto_wal_proto_init() }
func file_modules_wal_proto_wal_proto_init() {
	if File_modules_wal_proto_wal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_wal_proto_wal_proto_rawDesc), len(file_modules_wal_proto_wal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_modules_wal_proto_wal_proto_goTypes,
		DependencyIndexes: file_modules_wal_proto_wal_proto_depIdxs,
		MessageInfos:      file_modules_wal_proto_wal_proto_msgTypes,
	}.Build()
	File_modules_wal_proto_wal_proto = out.File
	file_modules_wal_proto_wal_proto_goTypes = nil
	file_modules_wal_proto_wal_proto_depIdxs = nil
}
